### ISSUE TITLE
Can I break this?

### ISSUE THREAD

**Issue by bepursuant** [IEvangelist/GitHub.ProfanityFilter#14]
:gift_heart:

**Comment by IEvangelist** [comment]
Interesting, so clearly it needs some improvement. Thanks for testing this, would you like to fork this, create a unit test with that input and implement a fix? I'd accept a pull request.

**Comment by bepursuant** [comment]
I considered putting together tests and submitting a pull request, but currently I don't have an idea for how to address these workarounds. But I think that they are edge cases, and the point of the filter is not to prevent clever bypasses, but to strip pedestrian profanity.

The first was just a Unicode "s-looking" character, and i don't know of any "characters that look alike" map - even if it exists, the implementation would be cumbersome (like, expanding out the regular expressions for every variant of every lookalike character), with little payoff given the goals of the library.

The second was just using markdown to bold a character in the middle of the word, so the string body of the issue doesn't match the regex. I don't see a field in the GitHub API that has the issue body with markdown stripped - even if that exists, or if we used something to strip the markdown ourselves, replacing the word there and updating the issue would strip all markdown from it, which could have some unintended consequences and be more problem than solution.

All together, I think these are more "known and accepted limitations" than bugs to be fixed.

I do intend to play around and maybe submit a different pull request for a new feature though - inspiration being https://youtu.be/Nfh92hKLO6c :)
